# MIT License
#
# Copyright (c) 2025 Rooam Lee
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
x-hadoop-common: &hadoop-common
  build:
    context: .
    dockerfile: Dockerfile
  image: hadoop:latest
  environment: &hadoop-common-env
    YARN_CONF_DIR: /opt/hadoop/etc/hadoop
  working_dir: /opt/hadoop
  volumes:
    - ${HADOOP_PROJ_DIR:-.}/jobs:/opt/hadoop/jobs
    - ${HADOOP_PROJ_DIR:-.}/logs:/opt/hadoop/logs
    - ${HADOOP_PROJ_DIR:-.}/config:/opt/hadoop/config
    - ${HADOOP_PROJ_DIR:-.}/plugins:/opt/hadoop/plugins
  user: "${HADOOP_UID:-hadoop}:0"

services:
  hadoop:
    <<: *hadoop-common
    command: standalone
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
      - "8080:8080"
    depends_on:
      init:
        condition: service_completed_successfully

  init:
    <<: *hadoop-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/jobs /sources/logs /sources/plugins
        chown -R "${HADOOP_UID}:0" /sources/{jobs,logs,plugins}
        hdfs version
    user: "0:0"
    volumes:
      - ${HADOOP_PROJ_DIR:-.}:/sources
