# MIT License
#
# Copyright (c) 2025 Rooam Lee
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
x-elasticsearch-common: &elasticsearch-common
  image: ${ELASTICSEARCH_IMAGE_NAME:-elasticsearch:8.19.0}
  environment: &elasticsearch-common-env
    cluster.name: "es-cluster"
    network.host: 0.0.0.0
    xpack.security.enabled: "false"
    bootstrap.memory_lock: "true"
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
    interval: 30s
    retries: 5
    start_period: 30s

services:
  es-node:
    <<: *elasticsearch-common
    hostname: es-node
    environment:
      <<: *elasticsearch-common-env
      node.name: "es-node"
      discovery.seed_hosts: "es-node,es-node-2"
      cluster.initial_master_nodes: "es-node,es-node-2"
    volumes:
      - es-node-volume:/usr/share/elasticsearch/data

  es-node-2:
    <<: *elasticsearch-common
    hostname: es-node-2
    environment:
      <<: *elasticsearch-common-env
      node.name: "es-node-2"
      discovery.seed_hosts: "es-node,es-node-2"
      cluster.initial_master_nodes: "es-node,es-node-2"
    volumes:
      - es-node-2-volume:/usr/share/elasticsearch/data

  logstash:
    build:
      context: logstash
      dockerfile: Dockerfile
    # image: ${LOGSTASH_IMAGE_NAME:-logstash:8.19.0}
    hostname: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/_node/stats"]
      interval: 30s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - ${ELK_PROJ_DIR:-.}/logs:/usr/share/logs
    depends_on:
      es-node:
        condition: service_healthy
      es-node-2:
        condition: service_healthy

  kibana:
    image: ${KIBANA_IMAGE_NAME:-kibana:8.19.0}
    hostname: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://es-node:9200"
    depends_on:
      es-node:
        condition: service_healthy
      es-node-2:
        condition: service_healthy

  filebeat:
    build:
      context: filebeat
      dockerfile: Dockerfile
    # image: ${FILEBEAT_IMAGE_NAME:-elastic/filebeat:8.19.0}
    hostname: filebeat
    volumes:
      - ${ELK_PROJ_DIR:-.}/logs:/usr/share/logs
    depends_on:
      logstash:
        condition: service_healthy

volumes:
  es-node-volume:
  es-node-2-volume:
